### ISSUE TITLE
build failures introduced in 869e7fe1916c

### ISSUE THREAD

**Issue by bertschinger** [PEAK-AIO/pnfs-lattice#2]
When trying to build the latest version of pnfs-core, I get build failures that seem to be introduced in the recent commit 869e7fe1916c0f12652b98846943dc5346254da7:

```bash
pnfs@mds1:~/pnfscore$ cmake --build build -j8
[  1%] Built target test_memdb
[  6%] Built target pnfs_common
[  7%] Built target rondb_schema
[ 10%] Built target pnfs_fsal_obj
[ 16%] Built target pnfs_cluster
[ 17%] Building C object src/mds/CMakeFiles/pnfs_mds_core.dir/layout_recall.c.o
/home/pnfs/pnfscore/src/mds/layout_recall.c: In function ‘byte_range_collect_cb’:
/home/pnfs/pnfscore/src/mds/layout_recall.c:758:9: error: implicit declaration of function ‘layout_seqid_peek’; did you mean ‘layout_ds_id_seen’? [-Wimplicit-function-declaration]
  758 |     if (layout_seqid_peek(effective_stateid.other, &latest_seqid) &&
      |         ^~~~~~~~~~~~~~~~~
      |         layout_ds_id_seen
/home/pnfs/pnfscore/src/mds/layout_recall.c: In function ‘byte_range_cb_one_holder’:
/home/pnfs/pnfscore/src/mds/layout_recall.c:946:5: error: implicit declaration of function ‘layout_seqid_record_at’ [-Wimplicit-function-declaration]
  946 |     layout_seqid_record_at(recall_stateid.other, recall_stateid.seqid);
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/pnfs/pnfscore/src/mds/layout_recall.c:947:5: error: implicit declaration of function ‘layout_seqid_advance’ [-Wimplicit-function-declaration]
  947 |     layout_seqid_advance(recall_stateid.other, &seqid_hit, &recall_seqid);
      |     ^~~~~~~~~~~~~~~~~~~~
/home/pnfs/pnfscore/src/mds/layout_recall.c: In function ‘byte_range_cb_status_transient’:
/home/pnfs/pnfscore/src/mds/layout_recall.c:1120:31: error: ‘NFS4ERR_RECALLCONFLICT’ undeclared (first use in this function)
 1120 |            (cb_status == (int)NFS4ERR_RECALLCONFLICT);
      |                               ^~~~~~~~~~~~~~~~~~~~~~
/home/pnfs/pnfscore/src/mds/layout_recall.c:1120:31: note: each undeclared identifier is reported only once for each function it appears in
/home/pnfs/pnfscore/src/mds/layout_recall.c: In function ‘byte_range_revoke_holders’:
/home/pnfs/pnfscore/src/mds/layout_recall.c:1158:9: error: implicit declaration of function ‘layout_seqid_remove’ [-Wimplicit-function-declaration]
 1158 |         layout_seqid_remove(holders[i].stateid.other);
      |         ^~~~~~~~~~~~~~~~~~~
gmake[2]: *** [src/mds/CMakeFiles/pnfs_mds_core.dir/build.make:499: src/mds/CMakeFiles/pnfs_mds_core.dir/layout_recall.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:855: src/mds/CMakeFiles/pnfs_mds_core.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

Some of the undefined functions like `layout_seqid_peek()` appear to be defined in the file `src/mds/compound_layout.c`. The function however is `static` in that file. Perhaps it meant to be defined in a header?

Others, like `layout_seqid_record_at()`, don't appear to be defined anywhere in the codebase.

The new enum value `NFS4ERR_RECALLCONFLICT` is used but not defined anywhere - presumably it should have been added to `enum nfs4_status` in `include/compound.h`?

Maybe there was an extra commit that defined these functions and constants that was accidentally omitted from the version pushed to github?

**Comment by bertschinger** [comment]
I see that this was partially resolved in 8a1a0a1653f4eb367073d6ecb44f2f60facfae7e, but there still seem to be unresolved build failures that were introduced in 869e7fe1. I now get these:
```
/home/pnfs/pnfscore/tests/unit/test_layout_recall.c:35:10: fatal error: compound_internal.h: No such file or directory
   35 | #include "compound_internal.h"
      |          ^~~~~~~~~~~~~~~~~~~~~

/home/pnfs/pnfscore/tests/unit/test_layout_recall.c: In function ‘test_byte_range_recall_revokes_on_nomatching_layout’:
/home/pnfs/pnfscore/tests/unit/test_layout_recall.c:1175:35: error: ‘NFS4ERR_NOMATCHING_LAYOUT’ undeclared (first use in this function)
 1175 |     mock.reply_status = (uint32_t)NFS4ERR_NOMATCHING_LAYOUT;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by elemberger-peak** [comment]
issue resolved in v0.2.0
